### ISSUE TITLE
LGPL linking exception

### ISSUE THREAD

**Issue by johnwhitington** [djs55/ocaml-sha#17]
I'm replacing my pure OCaml versions of the sha functions in CamlPDF, for speed, and I'd like to try ocaml-sha. However, since we distribute statically linked binaries, I can't do that. Would you consider adding the standard linking exception to your LGPL license?

This is the exception several OCaml projects use, for example X. Leroy's "CamlZip", which we already use. This is the modifying text, although you replace "INRIA" obviously:

```
As a special exception to the GNU Lesser General Public License, you
may link, statically or dynamically, a "work that uses the Library"
with a publicly distributed version of the Library to produce an
executable file containing portions of the Library, and distribute
that executable file under terms of your choice, without any of the
additional requirements listed in clause 6 of the GNU Lesser General
Public License.  By "a publicly distributed version of the Library",
we mean either the unmodified Library as distributed by INRIA, or a
modified version of the Library that is distributed under the
conditions defined in clause 3 of the GNU Lesser General Public
License.  This exception does not however invalidate any other reasons
why the executable file might be covered by the GNU Lesser General
Public License.
```

Whatever you decide, could you add a LICENSE file to the repository, to make it clear what license covers all the files?

**Comment by talex5** [comment]
ocaml-sha is now under the ISC License, so I think this can be closed.

**Comment by djs55** [comment]
Closing (2 years later...)
