### ISSUE TITLE
new maintainer(s)?

### ISSUE THREAD

**Issue by c-cube** [djs55/ocaml-sha#19]
Hi, the library is advertised as unmaintained, and PRs/issues are old. Would you mind if someone took over the project (keeping it in the same spirit, of course)? It looks pretty robust, but small improvements are always useful (for instance, I think some functions could release the GC lock). I volunteer if no one else wants…

**Comment by vincenthz** [comment]
I think someone took over the binding, but put it somewhere else. I'm not sure exactly. Otherwise I'm happy to transfer maintainer-ship one way or another.

**Comment by c-cube** [comment]
Well, looking at the issues and PRs, it seems you could add @dsheets or @ecc1 to the list of contributors, if they are willing to…

**Comment by madroach** [comment]
Hi,

I have some bugfixes and several improvements I'd like to get merged. Is there any active maintainer at the moment?
Is it possible to relicense to a more permissive license like ISC?

**Comment by ecc1** [comment]
On Tue, Jul 12, 2016 at 09:38:27AM -0700, madroach wrote:
> I have some bugfixes and several improvements I'd like to get merged. Is there
> any active maintainer at the moment?
> Is it possible to relicense to a more permissive license like ISC?

I maintain Vincent's package for Debian.  There is only one pending
patch for it in the Debian bug tracking system.

You're welcome to submit others, but it would be better for you to
work directly with Vincent on a new upstream version.

--
Eric Cooper             e c c @ c m u . e d u

**Comment by madroach** [comment]
I'd like to take maintainership.

**Comment by ecc1** [comment]
On Wed, Jan 18, 2017 at 12:28:00PM -0800, madroach wrote:
> I'd like to take maintainership.

I'm not sure if you're talking about the Debian package, the upstream
version, or both, but it's fine with me if you want to maintain the
Debian package.  Shall I orphan it?

--
Eric Cooper             e c c @ c m u . e d u

**Comment by madroach** [comment]
No, sorry I'm a BSD user, last time I used debian was ages ago. I'd like to maintain (or have an active maintainer to talk to) the upstream package.

**Comment by djs55** [comment]
Hi,

Vincent kindly transferred the repo over to me for some basic maintenance. I'm planning to go through the pull requests and issues over the weekend (starting with the relicensing to BSD which is covered by #22 -- I guess that should go first and then people who have written PRs should be asked if they're still ok contributing under those terms)

Thanks,
Dave
